CREATE TABLE `persona` (
  `idpersona` int(11) NOT NULL AUTO_INCREMENT,
  `apellido` varchar(100) NOT NULL,
  `nombre` varchar(50) NOT NULL,
  `dni` varchar(8) NOT NULL,
  `cuil` varchar(15) NOT NULL,
  `fechaNacimiento` date NOT NULL,
  `nacionalidad` varchar(45) NOT NULL,
  `localidad` int(11) NOT NULL,
  `codPostal` int(11) NOT NULL,
  `estadoCivil` varchar(10) NOT NULL,
  `genero` varchar(45) NOT NULL,
  `telefonoContacto` varchar(20) NOT NULL,
  `email` varchar(50) NOT NULL,
  `domicilio` varchar(100) NOT NULL,
  `comisariaJuris` varchar(80) NOT NULL,
  `nivelEducativo` varchar(40) NOT NULL,
  `establecimiento` varchar(200) NOT NULL,
  `tituloSecundario` varchar(100) NOT NULL,
  `oficio` varchar(45) DEFAULT NULL,
  `carrera` varchar(60) DEFAULT NULL,
  `tituloNS` varchar(45) DEFAULT NULL,
  `fechaIngreso` datetime NOT NULL,
  `decretoNro` varchar(45) NOT NULL,
  `reqEdad` varchar(12) DEFAULT NULL,
  `enviado` varchar(2) DEFAULT NULL,
  `fechaHoraEnvio` datetime DEFAULT NULL,
  `validado` varchar(2) DEFAULT NULL,
  `fechaHoraValidacion` datetime DEFAULT NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE KEY `dni_UNIQUE` (`dni`),
  KEY `idx_localidad` (`localidad`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4;